---
version: 2
multi-ecosystem-groups:
  deps:
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "11:00"
      timezone: "Europe/Brussels"
updates:
- package-ecosystem: "bundler"
  directory: "/"
  multi-ecosystem-group: "deps"
- package-ecosystem: "npm"
  directory: "/"
  multi-ecosystem-group: "deps"
- package-ecosystem: "docker"
  directory: "/"
  multi-ecosystem-group: "deps"
- package-ecosystem: "docker-compose"
  directory: "/"
  multi-ecosystem-group: "deps"
- package-ecosystem: "github-actions"
  directory: "/"
  multi-ecosystem-group: "deps"
