---
version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  ignore:
    - dependency-name: "bulma-rails"
      update-types: ["version-update:semver-major"]
    - dependency-name: "font-awesome-sass"
      update-types: ["version-update:semver-major"]
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "11:00"
    timezone: "Europe/Brussels"
  open-pull-requests-limit: 20

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "11:00"
    timezone: "Europe/Brussels"
  open-pull-requests-limit: 20

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "11:00"
    timezone: "Europe/Brussels"
  open-pull-requests-limit: 20

- package-ecosystem: "docker-compose"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "11:00"
    timezone: "Europe/Brussels"
  open-pull-requests-limit: 20

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "11:00"
    timezone: "Europe/Brussels"
  open-pull-requests-limit: 20
