---
version: 2
.common: &common
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "11:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
updates:
- package-ecosystem: bundler
  <<: *common
- package-ecosystem: npm
  <<: *common
- package-ecosystem: docker
  <<: *common
- package-ecosystem: docker-compose
  <<: *common
- package-ecosystem: github-actions
  <<: *common
